### CS4102 - Geometric Foundations of Data Analysis I
Prof. Götz Pfeiffer<br />
School of Mathematics, Statistics and Applied Mathematics<br />
NUI Galway

#### 1. Principal Component Analysis

# Week 7

## Numpy - a quick overview

* `numpy` is *the* library for matrix algebra in Python.
* Usually, it's name is abbreviated as `np`.

In [1]:
import numpy as np

###  Arrays

* The fundamental data type in numpy is `ndarray`, often just called 'array',
* We can use this data type for vectors and matrice .... 

In [2]:
np.array([1,7,3,4,9,11])  #  a vector

array([ 1,  7,  3,  4,  9, 11])

In [3]:
np.array([[3,5],[-1,2]])  # a matrix

array([[ 3,  5],
       [-1,  2]])

In [4]:
np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # a 3-dim'l tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Special Matrices

* There are commands for creating matrices of zeros or ones

In [5]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Reshaping

* Each array has a shape: its size in each dimension.
* The shape on an array can be modified

In [7]:
a = np.array(range(16))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
a.reshape(-1,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [10]:
a.reshape((2,2,2,2))

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

### Floating Point Ranges: `arange` vs. `linspace`

In [11]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.arange(1,32,2)  # start, stop (exclusive), stepsize

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [13]:
np.arange(1, 1.3, 0.1)  # exclusve?  yes but there are rounding errors

array([1. , 1.1, 1.2, 1.3])

In [14]:
np.linspace(1, 1.3, 4)  # start, stop (inclusive), count

array([1. , 1.1, 1.2, 1.3])

### Mathematical Operations

* We can use `+` and `-` for adding and subtracting matrices (of the same shape)

In [15]:
a = np.array(range(1,7)).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a + a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
a - a

array([[0, 0, 0],
       [0, 0, 0]])

* We can use `*` to multiply a matrix with a scalar ...

In [18]:
3 * a

array([[ 3,  6,  9],
       [12, 15, 18]])

In [19]:
a * 0

array([[0, 0, 0],
       [0, 0, 0]])

* ... but not for matrix multiplication :-(
* The `*` operator applied to matrices $A = (a_{ij})$ and $B= (b_{ij})$ (of the same shape) yields their *Hadamard product*:
that is the matrix $C = (c_{ij})$ (of the same shape as $A$ and $B$) with $c_{ij} = a_{ij} b_{ij}$

In [20]:
a * a

array([[ 1,  4,  9],
       [16, 25, 36]])